AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.3
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "lib/tasks/**/*"
    - "node_modules/**/*"
    - Gemfile
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
